import type { CourseReference } from "../reference";

export const introCircuits: CourseReference = {
  formulaLabels: {
    "current/definition": "Current and the ampere",
    "voltage/potential": "Voltage and the volt",
    "resistance/ohm": "Ohm's law",
    "resistance/resistivity": "Resistance from resistivity",
    "resistance/power": "Electric power in a resistor",
    "series/series": "Series resistances",
    "series/kvl": "Kirchhoff's voltage law",
    "series/divider": "Voltage divider",
    "parallel/kcl": "Kirchhoff's current law",
    "parallel/parallel": "Parallel resistances",
    "ac/sine": "AC voltage",
    "ac/rms": "RMS value and average AC power",
    "impedance/capacitor": "Capacitor energy and RC charging",
    "impedance/impedance": "Impedance and Ohm's law for AC",
    "sync/generator": "Mechanical and electrical power of a generator",
  },
  extraFormulas: [
    { chapterId: "current", label: "Faraday constant (charge of one mole of electrons)", tex: "F = N_A\\,e \\approx 96\\,485\\ \\mathrm{C/mol}" },
    { chapterId: "impedance", label: "Energy stored in an inductor", tex: "W = \\tfrac{1}{2} L\\,i^2" },
    { chapterId: "power-electronics", label: "Average voltage from switching (duty cycle D)", tex: "V_{avg} = D\\,V_{source}" },
  ],
  definitions: [
    { term: "Current", chapterId: "current", text: "Charge passing a point per second, i = dq/dt. 1 A = 1 C/s. Conventional current flows opposite to the electrons." },
    { term: "Coulomb", chapterId: "current", text: "The unit of charge: about 6.24 × 10¹⁸ electrons. Not a mole of electrons — that is 96 485 C, the Faraday constant." },
    { term: "Dangerous current", chapterId: "current", text: "About 1 mA through the body is felt, ~10 mA can stop you letting go, and ~50–100 mA across the chest can cause ventricular fibrillation." },
    { term: "Voltage", chapterId: "voltage", text: "The difference in electric potential between two points: energy per unit charge, 1 V = 1 J/C. Always measured between two points." },
    { term: "Resistance", chapterId: "resistance", text: "A property of a specific component: the voltage needed per ampere of current, R = V/I, in ohms." },
    { term: "Resistivity (ρ)", chapterId: "resistance", text: "A property of the material. Resistance follows from it and the geometry: R = ρL/A." },
    { term: "Kirchhoff's voltage law (KVL)", chapterId: "series", text: "Around any closed loop the voltages sum to zero: energy gained equals energy given away." },
    { term: "Kirchhoff's current law (KCL)", chapterId: "parallel", text: "The algebraic sum of currents into a node is zero: charge cannot pile up." },
    { term: "Parallel connection", chapterId: "parallel", text: "Branches share the same voltage and their currents add, so the total resistance is lower than the smallest branch." },
    { term: "RMS value", chapterId: "ac", text: "The root mean square of an AC signal, V_max/√2 for a sine; 325 V peak gives 230 V RMS. Average power is V_rms · I_rms." },
    { term: "Three-phase power", chapterId: "ac", text: "Three sine waves 120° apart; their powers sum to a constant, which is why generators and large motors use it." },
    { term: "Impedance (Z)", chapterId: "impedance", text: "The AC generalisation of resistance, Z = R + jX, including the reactance of capacitors and inductors. It has a magnitude and a phase and depends on frequency." },
    { term: "Inertia", chapterId: "sync", text: "The kinetic energy of all synchronised rotating generators. It absorbs sudden power imbalances and slows the frequency change." },
    { term: "Grid frequency", chapterId: "sync", text: "50 Hz in Europe. It falls when consumption exceeds production and rises when production exceeds consumption." },
    { term: "Primary frequency control", chapterId: "frequency", text: "Automatic reserves that react within seconds to stop a frequency deviation, stabilising it close to but not at 50 Hz." },
    { term: "Secondary frequency control", chapterId: "frequency", text: "Reserves activated within minutes that bring the frequency back to 50 Hz and free the primary reserves." },
    { term: "Rectifier / inverter", chapterId: "power-electronics", text: "A rectifier converts AC to DC; an inverter converts DC to AC at the grid's voltage, frequency and phase. A transformer only changes voltage." },
  ],
};
