import type { CourseReference } from "../reference";

export const introEnergy: CourseReference = {
  formulaLabels: {
    "thermo/carnot": "Carnot efficiency (worked example, 100 °C → 4 °C)",
    "compare/energy-power": "Discharge duration",
    "hydro/gravity": "Gravitational energy: 1 t lifted 100 m",
    "mech-thermal/flywheel": "Energy in a flywheel",
    "fuels/routes": "Sabatier and Haber–Bosch reactions",
    "electromagnetic/mechanism": "Energy in a capacitor and in a superconducting coil",
    "economics/capex": "Storage cost per kWh vs duration",
    "chemistries/alkaline": "Alkaline cell reaction",
    "chemistries/nicd": "Ni-Cd cell reaction",
    "testing/voltage": "Cell voltage from electrode potentials",
    "testing/efficiency": "Coulombic vs energy efficiency",
  },
  extraFormulas: [
    { chapterId: "compare", label: "Round-trip efficiency", tex: "\\eta_{rt} = \\frac{E_{out}}{E_{in}}" },
    { chapterId: "economics", label: "Capital cost", tex: "\\text{CAPEX} = C_{power}\\,P + C_{energy}\\,E" },
    { chapterId: "fuels", label: "Water electrolysis", tex: "2\\,\\mathrm{H_2O} \\rightarrow 2\\,\\mathrm{H_2} + \\mathrm{O_2}" },
  ],
  definitions: [
    { term: "First law of thermodynamics", chapterId: "thermo", text: "Energy is conserved: never created or destroyed, only converted. Storage cannot create energy; what is not delivered became (mostly) heat." },
    { term: "Second law of thermodynamics", chapterId: "thermo", text: "Energy has quality. High-quality energy converts completely into low-quality energy, but not all heat can become work." },
    { term: "Energy quality", chapterId: "thermo", text: "High: electricity, mechanical work, gravitational and kinetic energy. Low: heat near ambient temperature. High quality converts to anything efficiently." },
    { term: "Carnot limit", chapterId: "thermo", text: "The maximum efficiency of any heat engine, 1 − T_L/T_H with temperatures in kelvin. Storage that never goes via heat is not bound by it." },
    { term: "Net load", chapterId: "why-storage", text: "Demand minus variable renewable generation. With more solar it dips at midday and ramps steeply in the evening." },
    { term: "Peak shaving", chapterId: "why-storage", text: "Charging when demand and prices are low and discharging at the peak, lowering the maximum load." },
    { term: "Energy capacity vs power rating", chapterId: "compare", text: "Energy (kWh) sets how long a store can supply; power (kW) sets how much at once. Duration = energy / power." },
    { term: "Specific energy / energy density", chapterId: "compare", text: "Energy per kilogram (Wh/kg, gravimetric) vs energy per litre (Wh/L, volumetric)." },
    { term: "Round-trip efficiency", chapterId: "compare", text: "Energy out divided by energy in over a full cycle. Always check where the system boundary is drawn." },
    { term: "Self-discharge", chapterId: "compare", text: "Energy lost while stored: flywheels lose percent per hour, Li-ion percent per month, fuels almost nothing." },
    { term: "Cycle life / calendar life", chapterId: "compare", text: "Cycles until capacity falls to ~80 %, and ageing that happens with time whether the store is used or not." },
    { term: "Pumped hydro storage", chapterId: "hydro", text: "Water pumped to an upper reservoir when power is cheap and released through turbines later. The only hydro type rechargeable from the grid." },
    { term: "Diabatic vs adiabatic CAES", chapterId: "mech-thermal", text: "Diabatic compressed-air storage dumps the compression heat and burns gas on discharge (~42 %); adiabatic stores the heat and reuses it (~70 %)." },
    { term: "Sensible, latent, thermochemical heat", chapterId: "mech-thermal", text: "Raising a material's temperature, melting it at constant temperature, or driving a reversible reaction — increasing energy density and complexity." },
    { term: "Power-to-X", chapterId: "fuels", text: "Using (surplus) electricity to make a storable fuel or chemical: hydrogen by electrolysis, then methane, methanol or ammonia." },
    { term: "Hydrogen colours", chapterId: "fuels", text: "Grey: natural gas, CO₂ released. Blue: with carbon capture. Green: renewable electrolysis. Pink: nuclear electrolysis." },
    { term: "SMES", chapterId: "electromagnetic", text: "Superconducting magnetic energy storage: current circulating without loss in a cooled coil, E = ½LI². ~5 ms response, very high cost per kWh." },
    { term: "Energy arbitrage", chapterId: "economics", text: "Buying electricity when it is cheap and selling when it is expensive; profitable only if the spread beats losses and degradation." },
    { term: "LCOS", chapterId: "economics", text: "Levelised cost of storage: the price per MWh discharged that pays back all lifetime costs. Utilisation is the biggest lever." },
    { term: "Primary vs secondary battery", chapterId: "chemistries", text: "A primary cell is used once (e.g. alkaline); a secondary cell is rechargeable (e.g. Li-ion, Ni-Cd)." },
    { term: "Metal–air battery", chapterId: "chemistries", text: "A metal anode with an air-breathing cathode that takes O₂ from the air: high energy density, poor rechargeability and low power." },
    { term: "Coulombic vs energy efficiency", chapterId: "testing", text: "CE = charge out / charge in. EE = energy out / energy in, which also counts voltage, so EE is always lower." },
    { term: "Ohmic, activation, concentration losses", chapterId: "testing", text: "Voltage losses from resistance (instant), charge-transfer kinetics (ms) and mass transport (seconds and longer)." },
    { term: "Standard potential", chapterId: "testing", text: "An electrode's potential under standard conditions relative to the standard hydrogen electrode (0 V); cell voltage = E_cathode − E_anode." },
  ],
};
