import type { CourseReference } from "../reference";

export const materials: CourseReference = {
  formulaLabels: {
    "bonding/lattice-energy": "Born–Landé lattice energy",
    "miller/bragg": "Bragg's law",
    "solutions/carbon-iron": "Largest interstitial holes in fcc and bcc iron",
    "thermo/gibbs": "Gibbs free energy and spontaneity",
    "thermo/phase-rule": "Gibbs phase rule",
    "thermo/tangent": "Equilibrium between two phases (common tangent)",
    "binary/pbsn-above": "Lever rule: liquid in Pb–40Sn just above 183 °C",
    "binary/pbsn-below": "Lever rule: Pb-rich α in Pb–40Sn just below 183 °C",
    "binary/steel": "Lever rule: cementite in a 1.2 % C steel",
    "binary/pearlite": "Lever rule: austenite that becomes pearlite (1.2 % C, 727 °C)",
    "diffusion/fick": "Fick's first and second laws",
    "diffusion/arrhenius": "Temperature dependence of diffusion",
    "diffusion/erf": "Carburisation: error-function solution",
    "nucleation/balance": "Free energy of a spherical nucleus",
    "nucleation/critical": "Critical radius and nucleation barrier",
    "nucleation/undercooling": "Driving force from undercooling",
    "ttt/avrami": "Avrami equation",
  },
  extraFormulas: [
    { chapterId: "binary", label: "Lever rule (fraction of melt)", tex: "w_L = \\frac{C_\\alpha - C_0}{C_\\alpha - C_L}" },
    { chapterId: "diffusion", label: "Time to reach a depth x", tex: "t = \\frac{x^2}{4 D z^2}" },
    { chapterId: "nucleation", label: "Heterogeneous nucleation barrier", tex: "\\Delta G^*_{het} = S(\\theta)\\,\\Delta G^*_{hom},\\quad S(\\theta) = \\frac{2 - 3\\cos\\theta + \\cos^3\\theta}{4}" },
    { chapterId: "nucleation", label: "Hall–Petch relation", tex: "\\sigma_y = \\sigma_0 + \\frac{K}{\\sqrt{d}}" },
    { chapterId: "defects", label: "Vacancy concentration", tex: "c_v = e^{\\Delta S_v/k}\\,e^{-\\Delta H_v/kT}" },
  ],
  definitions: [
    { term: "Metallic, ionic, covalent bonding", chapterId: "bonding", text: "Metal–metal: a sea of shared valence electrons. Metal–non-metal: electrons transferred between ions. Non-metal–non-metal: electrons shared in directional bonds." },
    { term: "Lattice energy", chapterId: "bonding", text: "The energy needed to break an ionic crystal into gaseous ions. It grows with the ion charges and falls with the ion distance (MgO ≫ NaF > NaCl)." },
    { term: "Atomic packing factor", chapterId: "packing", text: "The fraction of the cell volume filled by atoms: 0.68 for bcc, 0.74 for fcc (ccp) and hcp." },
    { term: "Octahedral and tetrahedral voids", chapterId: "packing", text: "Interstitial sites between packed atoms. Cubic close packing has 1 octahedral and 2 tetrahedral voids per atom." },
    { term: "Radius ratio", chapterId: "packing", text: "r₊/r₋ decides the highest coordination a cation can take while touching its anions: > 0.225 tetrahedral, > 0.414 octahedral, > 0.732 cubic." },
    { term: "Miller indices (hkl)", chapterId: "miller", text: "A plane's name: intercepts on a, b, c in cell units, reciprocals, fractions cleared. A plane parallel to an axis has index 0 there." },
    { term: "Bragg's law", chapterId: "miller", text: "2d sin θ = nλ: X-rays reflected from planes with spacing d interfere constructively only at these angles." },
    { term: "Stacking fault", chapterId: "defects", text: "An error in the layer sequence, e.g. ABCAB|A|BC in a ccp metal, giving a thin hcp-like ABAB region." },
    { term: "Surface energy", chapterId: "defects", text: "The extra energy of surface atoms, which have lost bonded neighbours (a ccp (111) atom keeps 9 of 12). It follows bond strength, like the melting point." },
    { term: "Dislocation", chapterId: "defects", text: "A line defect whose glide carries plastic deformation; blocking it with grain boundaries, solutes or precipitates hardens a material." },
    { term: "Chemical potential (μ)", chapterId: "thermo", text: "The change in G per mole of a component added. At equilibrium each component has the same μ in every phase." },
    { term: "Gibbs phase rule", chapterId: "thermo", text: "p + f = c + 2, or p + f = c + 1 at constant pressure: phases plus degrees of freedom equal components plus the fixed variables." },
    { term: "Common tangent", chapterId: "thermo", text: "A line touching the G curves of two phases; its touching points give the equilibrium compositions because μ_A and μ_B are equal in both phases." },
    { term: "Liquidus and solidus", chapterId: "binary", text: "The borders of a two-phase region towards the melt and towards the solid." },
    { term: "Lever rule", chapterId: "binary", text: "The fraction of a phase is the length of the tie-line arm on the opposite side, divided by the whole tie line." },
    { term: "Eutectic / peritectic", chapterId: "binary", text: "Eutectic: melt → α + β. Peritectic: melt + α → β. Both are invariant points with 3 phases and 0 degrees of freedom." },
    { term: "Gibbs triangle", chapterId: "ternary", text: "An isothermal section of a ternary system: corners are pure elements, sides are binaries; compositions are read with lines parallel to the sides." },
    { term: "Fick's laws", chapterId: "diffusion", text: "First: the flux is proportional to the concentration gradient. Second: the concentration changes with the curvature of the profile." },
    { term: "Grain-boundary diffusion", chapterId: "diffusion", text: "Diffusion along less dense, disordered boundaries, faster than in the bulk; D_surface > D_GB > D_bulk." },
    { term: "Carburisation", chapterId: "diffusion", text: "Surface hardening by diffusing carbon into steel from a gas held at a constant surface concentration." },
    { term: "Critical radius (r*)", chapterId: "nucleation", text: "The nucleus size at the top of the ΔG(r) barrier: smaller nuclei dissolve, larger ones grow." },
    { term: "Undercooling", chapterId: "nucleation", text: "Cooling below the equilibrium temperature, needed to create a driving force for nucleation." },
    { term: "Heterogeneous nucleation", chapterId: "nucleation", text: "Nucleation on walls or particles, which lowers the barrier so only a few degrees of undercooling are needed." },
    { term: "Coring", chapterId: "solidification", text: "A composition gradient inside grains when solid-state diffusion is too slow for equilibrium, typical after peritectic reactions." },
    { term: "Constitutional undercooling", chapterId: "solidification", text: "Undercooling ahead of a growth front caused by rejected solute lowering the local liquidus temperature; it leads to dendrites." },
    { term: "TTT diagram", chapterId: "ttt", text: "Time–temperature–transformation curves; the nose appears because diffusion is slow at low T and the driving force is small at high T." },
    { term: "Martensite", chapterId: "ttt", text: "A body-centred tetragonal phase formed from austenite by diffusionless collective shear during rapid quenching; hard but brittle." },
    { term: "Age hardening", chapterId: "ttt", text: "Quench to a supersaturated solid solution, then age at low temperature so coherent precipitates form and block dislocations." },
    { term: "Austenite / ferrite / cementite", chapterId: "steels", text: "fcc γ-Fe, bcc α-Fe and Fe₃C. Pearlite is lamellar ferrite + cementite formed at the eutectoid (0.76 wt% C, 727 °C)." },
    { term: "Schaeffler diagram", chapterId: "steels", text: "Ni equivalent (austenite stabilisers) against Cr equivalent (ferrite stabilisers), predicting austenitic, ferritic, martensitic or mixed steel." },
    { term: "Duplex steel", chapterId: "steels", text: "About 50 % austenite and 50 % ferrite: high strength with excellent corrosion resistance." },
    { term: "γ′ precipitates", chapterId: "alloys", text: "Coherent ordered precipitates in the fcc γ matrix of Ni-based superalloys that give high strength and creep resistance." },
    { term: "Creep", chapterId: "alloys", text: "Time-dependent deformation under a constant load, important at high temperature." },
    { term: "Specific strength", chapterId: "alloys", text: "Strength divided by density; decisive when mass matters." },
  ],
};
